name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Start Backend Server
        run: npm start -- --configuration=test &
      - name: Start Frontend Server
        run: npm run start:ci
      - name: Run Tests
        run: npm test
